SET SQL_SAFE_UPDATES = 0;
USE hr;
SELECT MAX(SALARY) AS MAIOR_SALARIO FROM employees;

SELECT (MAX(SALARY) - MIN(SALARY)) AS MAIO_DIFF FROM employees;

SELECT AVG(SALARY) AS MEDIA, JOB_ID FROM employees 
	GROUP BY JOB_ID
    ORDER BY MEDIA DESC;
    
SELECT ROUND(SUM(SALARY) , 2) AS TOTAL_SALARIOS FROM employees;

SELECT 
	ROUND(MAX(SALARY), 2) AS MAIOR_SALARIO,
	ROUND(MIN(SALARY), 2) AS MENOR_SALARIO,
    ROUND(AVG(SALARY), 2) AS MÉDIA_SALARIAL,
    ROUND(SUM(SALARY), 2) AS TOTAL_SALARIOS
FROM employees;

SELECT COUNT(JOB_ID) AS QUANTITY_PROGRAMERS FROM employees
	GROUP BY JOB_ID
    HAVING JOB_ID = 'IT_PROG';

SELECT SUM(SALARY) AS TOTAL_SALARY_GRP, JOB_ID FROM employees 
	GROUP BY JOB_ID
    ORDER BY TOTAL_SALARY_GRP;

SELECT JOB_ID, ROUND(AVG(SALARY), 2) AS QUANTITY_PROGRAMERS FROM employees
	GROUP BY JOB_ID
    HAVING JOB_ID <> 'IT_PROG';
    
SELECT 
	ROUND(AVG(SALARY), 2) AS MÉDIA_SALARIOS,
	COUNT(DEPARTMENT_ID) AS NUM_FUNCIONARIOS
FROM employees
	GROUP BY DEPARTMENT_ID
    HAVING NUM_FUNCIONARIOS > 10;

SELECT PHONE_NUMBER FROM employees;

UPDATE employees
SET PHONE_NUMBER = REPLACE(PHONE_NUMBER, '515', '777');

SELECT * FROM employees
	WHERE LENGTH(FIRST_NAME) >= 8;

SELECT
	EMPLOYEE_ID,
    FIRST_NAME,
    YEAR(HIRE_DATE) AS HIRE_YEAR
FROM employees;

SELECT
	EMPLOYEE_ID,
    FIRST_NAME,
    DAY(HIRE_DATE) AS HIRE_DAY
FROM employees;

SELECT
	EMPLOYEE_ID,
    FIRST_NAME,
    MONTH(HIRE_DATE) AS HIRE_MONTH
FROM employees;

SELECT UCASE(CONCAT(FIRST_NAME, ' ', LAST_NAME)) AS NAME FROM employees;

SELECT LAST_NAME, HIRE_DATE FROM employees
	WHERE YEAR(HIRE_DATE) = 1987 AND MONTH(HIRE_DATE) = 07;

SELECT 
	FIRST_NAME,
	LAST_NAME, 
    DATEDIFF(NOW(), HIRE_DATE) AS TOTAL_DAYS
FROM employees;

